{application,phoebus_algos,
             [{description,[]},
              {vsn,"0.0.1"},
              {modules,[phoebus_algo_shortest_path,
			phoebus_algo_path_find
			]},
              {registered,[]},
              {applications,[kernel
			,stdlib]},
              {mod,{algos_app,[]}},
              {env,[]}]}.
